<?php


      $config = Mage::getStoreConfig('payment/pitchinpal/merchant_id');

      $total = Mage::getSingleton('checkout/session')->getQuote()->getGrandTotal();
      $shipmentAmount = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getShippingAmount();
      $totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals(); //Total object
      $tax = 0;
      if(isset($totals['tax']) && $totals['tax']->getValue())
      {
        $tax = $totals['tax']->getValue(); //Tax value if present
      }

      $quote = Mage::helper('checkout/cart')->getCart()->getQuote();
      $valor = [];
      $items = [];
      $valor['base_url'] = Mage::getBaseUrl();
      $valor['store_identifier'] = $config;
      $valor['amount'] = $total;
      $valor['total_tax'] = $tax;
      $valor['total_shipping'] = $shipmentAmount;
      $cartItems = Mage::getSingleton('checkout/cart')->getQuote()->getItemsCollection();
      $options = array();
      $variables = array();

        foreach ($cartItems as $pitem) {
          $pro = Mage::getModel('catalog/product')->load($pitem->getProduct()->getId());
          //if($pro->isConfigurable())
          if($pro->getTypeId() == "simple"){
            $parentIds = Mage::getModel('catalog/product_type_grouped')->getParentIdsByChild($pro->getId());
            if(!$parentIds)
                $parentIds = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild($pro->getId());

            if(isset($parentIds[0])){
                $parent = Mage::getModel('catalog/product')->load($parentIds[0]);

                if($parent->isConfigurable())
                {
                  $productAttributeOptions = $parent->getTypeInstance(true)->getConfigurableAttributesAsArray($parent);
                  foreach ($productAttributeOptions as $productAttribute) {
                      //  echo "<pre>";print_r($productAttribute);
                       $allValues = array_column($productAttribute['values'], 'value_index');
                       $allLabelValues = array_column($productAttribute['values'], 'store_label');

                       $currentProductValue = $pro->getData($productAttribute['attribute_code']);
                       $attr = $pro->getResource()->getAttribute($productAttribute['attribute_code']);
                       $attribute_value = $attr ->getFrontend()->getValue($pro);
                      //print_r();
                      if (in_array($currentProductValue, $allValues)) {
                        $options[$parentIds[0]][$pitem->getProduct()->getId()][$productAttribute['attribute_id']] = $currentProductValue;
                        $variables[$parentIds[0]][$pitem->getProduct()->getId()][$productAttribute['label']] = $attribute_value;
                      }

                  }


                }
            }

          }
        }

      foreach ($quote->getAllItems() as $item) {
        STATIC $qty='';
        if($item->getProductType() == 'configurable')  //configurable products
        {
            $qty = $item->getQty();
            $parent_id = $item->getProductId();
            continue;
        }
        else                                            // non-configurable product
        {
            if (!$item->getParentItem())               // products which have not parent product
            {
                $qty = $item->getQty();
                $parent_id = 0;
            }
        }

        if ('simple' != $item->getProductType()) continue;
        $product_image = (string)Mage::helper('catalog/image')->init($item->getProduct(), 'thumbnail')->resize(100);
        $product = $item->getProduct();
        $productUrl = $product->getUrlModel()->getUrl($product);
        $items= array (
           'id' => $item->getProductId(),
           'name'=> $item->getName(),
            'url_pro'=> $productUrl,
            'image' => $product_image,
            //'image' => 'http://lorempixel.com/g/400/200/',
                'sku' => $item->getSku(),
                'quantity' => $qty,
                'price' => $item->getParentItemId() ? $item->getParentItem()->getPrice() : $item->getPrice(),
                'type'  => $item->getProductType(),
                'variation_id' => isset($options[$parent_id][$item->getProductId()]) ? $options[$parent_id][$item->getProductId()]:0,
                'variables' => isset($variables[$parent_id][$item->getProductId()]) ? $variables[$parent_id][$item->getProductId()]:0,
        );

        $valor['items'][] = $items;
      }
//echo "<pre>";print_r($valor);
$pitchinpal_urlToSend = http_build_query($valor);
?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">

 <input type="hidden"  name="pitchinpal_urlToSend"  id="pitchinpal_urlToSend"
 value="<?php echo $pitchinpal_urlToSend;?>"/>



<div id="go_for_crowd_fund" style="display:none;">
  <div>
    <label><?php echo $this->__('Go for Crowd Fund') ?>*</label>
    <span>
      <input type="checkbox" title="<?php echo $this->__('Go for Crowd Fund') ?>" name="payment[custom_field_one]" id="checkbox_crowdfund" />
    </span>
  </div>
</div> <!-- End of go for crowd fund -->

<div id="pay_with_pitchinpal" style="display:none;">
  <div>
    <label><?php echo $this->__('Your Unique PitchinPal Key') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Your Unique PitchinPal Key') ?>" name="payment[custom_field_two]"  id="text_pitchinpal"/>
      <p style="font-size:10px;">*you can find this under your profile at PitchinPal.com</p>
    </span>
  </div>
        <div>
            <label><?php echo $this->__('If you do not have enough PitchinPal™ FriendFunds™, you can check this box to pay the difference by credit card.') ?>*</label>
            <span>
              <input type="checkbox" title="<?php echo $this->__('If you do not have enough PitchinPal™ FriendFunds™, you can check this box to pay the difference by credit card.') ?>" name="payment[custom_paycard]" value="1" onClick="showPartialPay(this);" id="checkbox_partial"/>
            </span>
                <div id="customcardpay" style="display:none;">
                     <div>
                          <label><?php echo $this->__('Credit Card Number') ?>*</label>
                          <span>
                            <input type="text" title="<?php echo $this->__('Credit Card Number') ?>" name="payment[custom_card_number]"  id="text_card_number" />
                          </span>
                      </div>

                      <div>
                          <label><?php echo $this->__('Expiration Month') ?>*</label>
                          <span>
                           <select  name="payment[custom_card_month]" id="select_month">

                              <option value="1">January</option>
                              <option value="2">February</option>
                              <option value="3">March</option>
                              <option value="4">April</option>
                              <option value="5">May</option>
                              <option value="6">June</option>
                              <option value="7">July</option>
                              <option value="8">August</option>
                              <option value="9">September</option>
                              <option value="10">October</option>
                              <option value="11">November</option>
                              <option value="12">December</option>
                            </select>
                          </span>
                      </div>

                       <div>
                          <label><?php echo $this->__('Expiration Year') ?>*</label>
                          <span>
                         <select name="payment[custom_card_year]" id="select_year">
                              <?php
                                 for($i = date('Y'); $i < date('Y')+10; $i++){
                                    echo "<option value='".$i."'>$i</option>";
                                 }
                              ?>
                          </select>
                          </span>
                      </div>
                       <div>
                          <label><?php echo $this->__('CVV Number') ?>*</label>
                          <span>
                            <input type="text" title="<?php echo $this->__('CVV Number') ?>" name="payment[custom_card_cvv]"  id="text_cvv"/>
                          </span>
                      </div>




                </div>
        </div>

      </div>  <!--End of pay with pitchinpal -->



 <div id='pitchinpal_title' style="width:100%;clear:both;">
 <span class="pitchinpal_meta"><br />PitchinPal is a great way to FriendFund your shopping cart. Fund the whole amount or even a portion with your PitchinPal FriendFunds.</span>
  <br />
          <div style="float:left;margin-right:10px;">
            <input type="submit" class="button" name="magento_checkout_have_crowdfund" id="have_crowdfund" value="Have PitchinPal FriendFunds" style="padding:5px 5px;">
            <div style="font-size:12px;">I have PitchinPal FriendFunds and  i am ready <br />to complete my purchase</div>
          </div>
          <div style="float:left;">
            <input type="submit" class="button" name="magento_checkout_go_crowdfund" id="go_crowdfund" value="Need PitchinPal FriendFunds" data-value="Go Crowdfund" style="padding:5px 5px;">
             <div style="font-size:12px;">I want to FriendFund With PitchinPal</div>
           </div>

</div> <!-- End of pitchinpal title -->

<div style="clear:both;"></div>

</div><!-- End of form-->







<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
